bufete:
    resource: "@BufeteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

Paises:
    resource: "@BufeteBundle/Resources/config/routing/paises.yml"
    prefix:     /paises

Departamentos:
    resource: "@BufeteBundle/Resources/config/routing/departamentos.yml"
    prefix:     /departamentos

Ciudades:
    resource: "@BufeteBundle/Resources/config/routing/ciudad.yml"
    prefix:     /ciudad

EstadosCiviles:
    resource: "@BufeteBundle/Resources/config/routing/estadosciviles.yml"
    prefix:     /estadosciviles

Bufetes:
    resource: "@BufeteBundle/Resources/config/routing/bufetes.yml"
    prefix:     /bufetes

Trabajos:
    resource: "@BufeteBundle/Resources/config/routing/trabajos.yml"
    prefix:     /trabajos

TipoAsunto:
    resource: "@BufeteBundle/Resources/config/routing/tipoasunto.yml"
    prefix:     /tipoasunto

Tribunales:
    resource: "@BufeteBundle/Resources/config/routing/tribunales.yml"
    prefix:     /tribunales
