revisiones_envioCorreo:
    path:     /envioCorreo
    defaults: { _controller: "BufeteBundle:Revisiones:envioCorreo" }
    methods:  GET

revisiones_indexRevisiones:
    path:     /indexRevisiones
    defaults: { _controller: "BufeteBundle:Revisiones:indexRevisiones" }
    methods:  GET

revisiones_indexInformes:
    path:     /indexInformes
    defaults: { _controller: "BufeteBundle:Revisiones:indexInformes" }
    methods:  GET

revisiones_indexLink:
    path:     /indexLink
    defaults: { _controller: "BufeteBundle:Revisiones:indexLink" }
    methods:  [GET, POST]

revisiones_indexLinkCaso:
    path:     /indexLinkCaso
    defaults: { _controller: "BufeteBundle:Revisiones:indexLinkCaso" }
    methods:  [GET, POST]

revisiones_indexLinkCasoEst:
    path:     /indexLinkCasoEst
    defaults: { _controller: "BufeteBundle:Revisiones:indexLinkCasoEst" }
    methods:  [GET, POST]

revisiones_showInforme:
    path:     /{idRevision}/showInforme
    defaults: { _controller: "BufeteBundle:Revisiones:showInforme" }
    methods:  GET

revisiones_showRevision:
    path:     /{idRevision}/showRevision
    defaults: { _controller: "BufeteBundle:Revisiones:showRevision" }
    methods:  GET

revisiones_showRevisionEstudiante:
    path:     /{idRevision}/showRevisionEstudiante
    defaults: { _controller: "BufeteBundle:Revisiones:showRevisionEstudiante" }
    methods:  GET

revisiones_showLink:
    path:     /{idRevision}/showLink
    defaults: { _controller: "BufeteBundle:Revisiones:showLink" }
    methods:  GET

revisiones_uploadRevision:
    path:     /uploadRevision
    defaults: { _controller: "BufeteBundle:Revisiones:uploadRevision" }
    methods:  [GET, POST]

revisiones_upload:
    path:     /upload
    defaults: { _controller: "BufeteBundle:Revisiones:upload" }
    methods:  [GET, POST]

revisiones_editRevision:
    path:     /editRevision
    defaults: { _controller: "BufeteBundle:Revisiones:editRevision" }
    methods:  [GET, POST]

revisiones_UploadEdit:
    path:     /UploadEdit
    defaults: { _controller: "BufeteBundle:Revisiones:UploadEdit" }
    methods:  [GET, POST]

revisiones_editLink:
    path:     /editLink
    defaults: { _controller: "BufeteBundle:Revisiones:editLink" }
    methods:  [GET, POST]

revisiones_newLink:
    path:     /newLink
    defaults: { _controller: "BufeteBundle:Revisiones:newLink" }
    methods:  [GET, POST]

revisiones_delete:
    path:     /{idRevision}/delete
    defaults: { _controller: "BufeteBundle:Revisiones:delete" }
    methods:  DELETE
