revisiones_indexRevisiones:
    path:     /indexRevisiones
    defaults: { _controller: "BufeteBundle:Revisiones:indexRevisiones" }
    methods:  GET

revisiones_indexInformes:
    path:     /indexInformes
    defaults: { _controller: "BufeteBundle:Revisiones:indexInformes" }
    methods:  GET



revisiones_showInforme:
    path:     /{idRevision}/showInforme
    defaults: { _controller: "BufeteBundle:Revisiones:showInforme" }
    methods:  GET

revisiones_showRevision:
    path:     /{idRevision}/showRevision
    defaults: { _controller: "BufeteBundle:Revisiones:showRevision" }
    methods:  GET

revisiones_new:
    path:     /new
    defaults: { _controller: "BufeteBundle:Revisiones:new" }
    methods:  [GET, POST]

revisiones_upload:
    path:     /upload
    defaults: { _controller: "BufeteBundle:Revisiones:upload" }
    methods:  [GET, POST]

revisiones_delete:
    path:     /{idRevision}/delete
    defaults: { _controller: "BufeteBundle:Revisiones:delete" }
    methods:  DELETE
